---
- name: ssh installed
  apt:
    name: openssh-server
    state: present

- name: copy ssh config file
  copy:
    src: sshd_config
    dest: /etc/ssh/sshd_config
    owner: root
    group: root
    mode: '-rw-r--r--'
  notify: restart ssh service

handlers:
  - name: restart ssh service
    service:
      name: ssh
      state: restarted
